repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
    - id: mypy
      exclude : >
        (?x)^(
          setup.py|
          versioneer.py|
          scripts/.*|
          doc/.*
        )$
