# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
dist: xenial

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

before_install:
  - pip install -r requirements.txt
  - pip install pre-commit
  - pip install -r requirements-test.txt

script:
  - pre-commit run --all-files
  - python -m pytest .
